import  type { Metadata } from "next"
import { Header } from "../components/Header"
import "../styles/globals.css";

export const metadata: Metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
children: React.ReactNode
}) {
	return (
    <html lang="ja">
		<body>
			<header>
				<h1 className="text-3xl font-bold underline">FullStack Todo --feat.Laravel10×Nextjs14</h1>
			</header>
			<main>
				{children}
			</main>
		</body>
    </html>
	)
}
