import  type { Metadata } from "next"
import { Header } from "../components/Header"
import "../styles/globals.css";

export const metadata: Metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
children: React.ReactNode
}) {
	return (
    <html lang="ja">
		<body>
			<Header />
			<main>
				{children}
			</main>
		</body>
    </html>
	)
}
